;this file for FamiTone2 library generated by text2data tool

pong_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $30 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $01
	.dw .env2,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $cd,$cb,$c8,$cb,$c8,$c0,$00,$05
.env2:
	.db $cf,$cf,$c9,$c9,$ca,$02,$cc,$00,$06


.song0ch0:
	.db $fb,$06
.song0ch0loop:
.ref0:
	.db $82,$3a,$8d,$38,$00,$8b,$3a,$8d,$3c,$00,$40,$00,$87
.ref1:
	.db $3a,$8d,$80,$3d,$41,$45,$43,$40,$85,$3c,$85,$3a,$8d
.ref2:
	.db $82,$44,$8d,$80,$42,$40,$3a,$89,$82,$44,$8d,$80,$4b,$4e,$89
.ref3:
	.db $82,$4a,$8d,$80,$4b,$4f,$53,$51,$4e,$85,$4a,$85,$48,$8d
.ref4:
	.db $bf
.ref5:
	.db $bf
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref6:
	.db $bf
.ref7:
	.db $bf
.ref8:
	.db $87,$80,$53,$35,$50,$4e,$4c,$89,$53,$52,$89,$55,$58,$89
.ref9:
	.db $82,$58,$8d,$80,$55,$53,$51,$4f,$4a,$85,$52,$85,$50,$8d
.ref10:
	.db $bf
.ref11:
	.db $bf
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref12:
	.db $80,$22,$85,$23,$21,$3a,$89,$25,$22,$85,$23,$21,$3d,$3a,$89
.ref13:
	.db $22,$85,$23,$21,$3a,$89,$25,$22,$85,$23,$21,$39,$3b,$29,$2a,$81
.ref14:
	.db $2c,$85,$2d,$2b,$44,$89,$2f,$2c,$85,$2d,$2b,$47,$44,$89
.ref15:
	.db $2c,$85,$2d,$2b,$44,$89,$2f,$2c,$85,$2d,$2b,$43,$41,$1f,$20,$81
.ref16:
	.db $22,$85,$23,$21,$3a,$89,$25,$22,$85,$23,$21,$3d,$3a,$89
	.db $ff,$10
	.dw .ref13
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref18:
	.db $bf
.ref19:
	.db $bf
.ref20:
	.db $bf
.ref21:
	.db $bf
.ref22:
	.db $bf
.ref23:
	.db $bf
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref24:
	.db $bf
.ref25:
	.db $bf
.ref26:
	.db $bf
.ref27:
	.db $bf
.ref28:
	.db $bf
.ref29:
	.db $bf
	.db $fd
	.dw .song0ch4loop
